name: Release Obsidian Plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Create release package
        run: |
          mkdir workspace-filegroups
          cp release/* workspace-filegroups/
          tar -czf workspace-filegroups-${{ github.ref_name }}.tar.gz workspace-filegroups/
          zip -r workspace-filegroups-${{ github.ref_name }}.zip workspace-filegroups/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            workspace-filegroups-${{ github.ref_name }}.tar.gz
            workspace-filegroups-${{ github.ref_name }}.zip
            release/main.js
            release/manifest.json
            release/styles.css
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 